# Generated by Django 2.2.1 on 2019-05-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=15, null=True)),
                ('card_limit', models.CharField(max_length=15, null=True)),
                ('card_status', models.CharField(max_length=15, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
